site_name: Pivot Atlas
site_url: https://gopivot.ing
repo_url: https://github.com/korniko98/pivot-atlas
repo_name: korniko98/pivot-atlas
edit_uri: edit/main/docs/
site_description: A pivoting handbook for cyber threat intel analysts
theme:
  name: material
  icon:
    logo: material/table-pivot
  favicon: images/favicon.png
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for dark mode
    - scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
plugins:
    - search
    - blog:
        archive: false
        blog_dir: updates
    - table-reader
    - mermaid2
    - git-committers:
        repository: korniko98/pivot-atlas
        branch: main
    - social:
        cards_layout: default/accent
        enabled: !ENV [CI, false]
    - rss:
        match_path: updates.posts.*
        date_from_meta:
          as_creation: date
markdown_extensions:
  - pymdownx.details
  - admonition
  - footnotes
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.pathconverter
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AmitaiCo
    - icon: fontawesome/solid/square-rss
      link: /feed_rss_created.xml
copyright: Maintained by <a href="https://twitter.com/AmitaiCo">Amitai Cohen</a>
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/wordflip.js